
import { ProxyNode } from './types';

export var MOCK_NODES: ProxyNode[] = [
  { id: 1, name: 'Loading ...', flag: '🇭🇰', countryCode: 'HK', latency: 45, host: 'hk1.minoproxy.com', port: 443, type: 'HTTPS' }
];

export function updateNodes(nodes: ProxyNode[]) {
    MOCK_NODES = nodes;
}

export const CN_DOMAIN_SUFFIXES = [
  "cn", "com.cn", "baidu.com", "qq.com", "taobao.com", "jd.com", "weibo.com", "alipay.com"
];

export const TRANSLATIONS = {
    en: {
        statusConnected: "CONNECTED",
        statusDisconnected: "DISCONNECTED",
        proxyMode: "Proxy Mode",
        smartMode: "Smart Mode",
        globalMode: "Global Mode",
        smartModeDesc: "Bypass CN domains & LAN",
        globalModeDesc: "Proxy all except LAN",
        currentLocation: "Current Location",
        selectServer: "Select Server",
        myAccount: "My Account",
        manageSub: "Manage subscription",
        guestUser: "Guest User",
        notLoggedIn: "Not logged in",
        loginRegister: "Login / Register",
        currentPlan: "Current Plan",
        member: "Member",
        upgrade: "Upgrade",
        subPlans: "Subscription Plans",
        recommended: "RECOMMENDED",
        selectPlan: "Select Plan",
        logout: "Log Out",
        login: "Login",
        register: "Register",
        email: "Email",
        password: "Password",
        processing: "Processing...",
        createAccount: "Create Account",
        signIn: "Sign In",
        haveAccount: "Already have an account?",
        noAccount: "Don't have an account?",
        language: "Language",
        proxy: "Proxy",
        me: "Me",
        close: "Close",
        secureAccess: "Secure access to the world",
        expires: "Expires"
    },
    zh: {
        statusConnected: "已连接",
        statusDisconnected: "未连接",
        proxyMode: "代理模式",
        smartMode: "智能模式",
        globalMode: "全局模式",
        smartModeDesc: "智能分流，绕过中国流量",
        globalModeDesc: "全局代理，仅直连局域网",
        currentLocation: "当前节点",
        selectServer: "选择服务器",
        myAccount: "我的账户",
        manageSub: "管理您的订阅和设置",
        guestUser: "游客用户",
        notLoggedIn: "未登录",
        loginRegister: "登录 / 注册",
        currentPlan: "当前方案",
        member: "会员",
        upgrade: "升级",
        subPlans: "订阅方案",
        recommended: "推荐",
        selectPlan: "选择方案",
        logout: "退出登录",
        login: "登录",
        register: "注册",
        email: "邮箱",
        password: "密码",
        processing: "处理中...",
        createAccount: "创建账户",
        signIn: "登录",
        haveAccount: "已有账户？",
        noAccount: "没有账户？",
        language: "语言设置",
        proxy: "代理",
        me: "我的",
        close: "关闭",
        secureAccess: "安全连接全世界",
        expires: "到期时间"
    },
    ru: {
        statusConnected: "ПОДКЛЮЧЕНО",
        statusDisconnected: "ОТКЛЮЧЕНО",
        proxyMode: "Режим прокси",
        smartMode: "Умный режим",
        globalMode: "Глобальный",
        smartModeDesc: "Обход локальных сетей",
        globalModeDesc: "Проксировать все",
        currentLocation: "Локация",
        selectServer: "Выбор сервера",
        myAccount: "Аккаунт",
        manageSub: "Управление подпиской",
        guestUser: "Гость",
        notLoggedIn: "Не авторизован",
        loginRegister: "Вход / Регистрация",
        currentPlan: "Ваш план",
        member: "Участник",
        upgrade: "Обновить",
        subPlans: "Тарифные планы",
        recommended: "ЛУЧШИЙ",
        selectPlan: "Выбрать",
        logout: "Выйти",
        login: "Вход",
        register: "Регистрация",
        email: "Email",
        password: "Пароль",
        processing: "Обработка...",
        createAccount: "Создать",
        signIn: "Войти",
        haveAccount: "Есть аккаунт?",
        noAccount: "Нет аккаунта?",
        language: "Язык",
        proxy: "Прокси",
        me: "Профиль",
        close: "Закрыть",
        secureAccess: "Безопасный доступ к миру",
        expires: "Истекает"
    },
    pt: {
        statusConnected: "CONECTADO",
        statusDisconnected: "DESCONECTADO",
        proxyMode: "Modo Proxy",
        smartMode: "Modo Inteligente",
        globalMode: "Modo Global",
        smartModeDesc: "Ignorar domínios locais",
        globalModeDesc: "Proxy para tudo",
        currentLocation: "Localização",
        selectServer: "Selecionar Servidor",
        myAccount: "Minha Conta",
        manageSub: "Gerenciar assinatura",
        guestUser: "Visitante",
        notLoggedIn: "Não logado",
        loginRegister: "Entrar / Registrar",
        currentPlan: "Plano Atual",
        member: "Membro",
        upgrade: "Melhorar",
        subPlans: "Planos de Assinatura",
        recommended: "RECOMENDADO",
        selectPlan: "Selecionar",
        logout: "Sair",
        login: "Entrar",
        register: "Registrar",
        email: "Email",
        password: "Senha",
        processing: "Processando...",
        createAccount: "Criar Conta",
        signIn: "Entrar",
        haveAccount: "Já tem conta?",
        noAccount: "Não tem conta?",
        language: "Idioma",
        proxy: "Proxy",
        me: "Eu",
        close: "Fechar",
        secureAccess: "Acesso seguro ao mundo",
        expires: "Expira em"
    }
};